# Generated by Django 5.1.4 on 2024-12-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancydescription',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Изображение'),
        ),
    ]
