# Generated by Django 5.1.4 on 2024-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_vacancydescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancydescription',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
