# Generated by Django 5.1.4 on 2024-12-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_vacancydescription_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancydescription',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
