# Generated by Django 5.1.4 on 2024-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_vacancydescription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_lvl_by_year', models.TextField(verbose_name='Данные таблицы "Динамика уровня зарплат по годам"')),
                ('salary_lvl_by_year_img', models.ImageField(upload_to='', verbose_name='График таблицы "Динамика уровня зарплат по годам"')),
            ],
        ),
    ]
