# Generated by Django 5.1.4 on 2024-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_generalstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalstatistics',
            name='salary_lvl_by_year_img',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='График таблицы "Динамика уровня зарплат по годам"'),
        ),
    ]
