# Generated by Django 5.1.4 on 2024-12-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_generalstatistics_salary_lvl_by_year_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryLevelByYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Данные')),
                ('salary_lvl_by_year', models.TextField(verbose_name='Данные таблицы "Динамика уровня зарплат по годам"')),
                ('salary_lvl_by_year_img', models.ImageField(null=True, upload_to='media/', verbose_name='График таблицы "Динамика уровня зарплат по годам"')),
            ],
            options={
                'verbose_name': 'Динамика уровня зарплат по годам',
                'verbose_name_plural': 'Динамики уровня зарплат по годам',
            },
        ),
        migrations.CreateModel(
            name='VacanciesCountByYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Данные')),
                ('vacs_cnt_by_year', models.TextField(verbose_name='Данные таблицы "Динамика количества вакансий по годам"')),
                ('vacs_cnt_by_year_img', models.ImageField(null=True, upload_to='media/', verbose_name='График таблицы "Динамика количества вакансий по годам"')),
            ],
            options={
                'verbose_name': 'Динамика количества вакансий по годам',
                'verbose_name_plural': 'Динамики количества вакансий по годам',
            },
        ),
        migrations.DeleteModel(
            name='GeneralStatistics',
        ),
    ]
