# Generated by Django 5.1.4 on 2024-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_salarylevelbyyeardata_vacanciescountbyyeardata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryLevelByAreaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Данные')),
                ('salary_lvl_by_area', models.TextField(verbose_name='Данные таблицы "Уровень зарплат по городам"')),
                ('salary_lvl_by_area_img', models.ImageField(null=True, upload_to='media/', verbose_name='График таблицы "Уровень зарплат по городам"')),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровни зарплат по городам',
            },
        ),
    ]
