# Generated by Django 5.1.4 on 2024-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_salarylevelbyareadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesFractionByAreaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Данные')),
                ('vacs_frac_by_area', models.TextField(verbose_name='Данные таблицы "Доля вакансий по городам"')),
                ('vacs_frac_by_area_img', models.ImageField(null=True, upload_to='media/', verbose_name='График таблицы "Доля вакансий по городам"')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доли вакансий по городам',
            },
        ),
    ]
