# Generated by Django 5.1.4 on 2024-12-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_vacanciesfractionbyareadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancydescription',
            options={'verbose_name': 'Описание профессии', 'verbose_name_plural': 'Описание профессий'},
        ),
    ]
