# Generated by Django 5.1.4 on 2024-12-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_vacancydescription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarylevelbyareadata',
            options={'verbose_name': 'Уровень зарплат по городам (Общая статистика)', 'verbose_name_plural': 'Уровни зарплат по городам (Общая статистика)'},
        ),
        migrations.AlterModelOptions(
            name='salarylevelbyyeardata',
            options={'verbose_name': 'Динамика уровня зарплат по годам (Общая статистика)', 'verbose_name_plural': 'Динамики уровня зарплат по годам (Общая статистика)'},
        ),
        migrations.AlterModelOptions(
            name='vacanciescountbyyeardata',
            options={'verbose_name': 'Динамика количества вакансий по годам (Общая статистика)', 'verbose_name_plural': 'Динамики количества вакансий по годам (Общая статистика)'},
        ),
        migrations.AlterModelOptions(
            name='vacanciesfractionbyareadata',
            options={'verbose_name': 'Доля вакансий по городам (Общая статистика)', 'verbose_name_plural': 'Доли вакансий по городам (Общая статистика)'},
        ),
        migrations.AlterModelOptions(
            name='vacancydescription',
            options={'verbose_name': 'Описание профессии (Главная страница)', 'verbose_name_plural': 'Описания профессий (Главная страница)'},
        ),
    ]
