# Generated by Django 5.1.4 on 2024-12-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_salarylevelbyareadata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancydescription',
            name='image',
        ),
        migrations.CreateModel(
            name='VacancyDescriptionPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Изображение')),
                ('vacancy_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.vacancydescription')),
            ],
        ),
    ]
