# Generated by Django 5.1.4 on 2024-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_vacancydescription_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancydescription',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='VacancyDescriptionPhotos',
        ),
    ]
