# Generated by Django 5.1.4 on 2024-12-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_vacancydescription_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top20KeySkillsByYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Данные')),
                ('top_20_key_skills_by_year', models.TextField()),
                ('top_20_key_skills_by_year_img', models.ImageField(null=True, upload_to='media/', verbose_name='График таблицы "Топ-20 навыков по годам"')),
            ],
            options={
                'verbose_name': 'Топ навыков по годам (Общая статистика)',
                'verbose_name_plural': 'Топы навыков по годам (Общая статистика)',
            },
        ),
    ]
