# Generated by Django 5.1.4 on 2025-01-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_top20keyskillsbyyeardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('table_data', models.TextField(verbose_name='Данные для таблицы')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Изображение графика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статистика вакансий',
                'verbose_name_plural': 'Статистики вакансий',
            },
        ),
    ]
