# Generated by Django 5.1.4 on 2025-01-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_vacancystatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancydescription',
            options={'verbose_name': 'Описание профессии', 'verbose_name_plural': 'Описания профессий'},
        ),
        migrations.AlterField(
            model_name='vacancystatistics',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название данных'),
        ),
    ]
