# Generated by Django 5.1.4 on 2025-01-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_vacancydescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancystatistics',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название данных ("Название вакансии")'),
        ),
    ]
