# Generated by Django 5.1.4 on 2025-01-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_vacancystatistics_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryLevelByAreaData',
        ),
        migrations.DeleteModel(
            name='SalaryLevelByYearData',
        ),
        migrations.DeleteModel(
            name='Top20KeySkillsByYearData',
        ),
        migrations.DeleteModel(
            name='VacanciesCountByYearData',
        ),
        migrations.DeleteModel(
            name='VacanciesFractionByAreaData',
        ),
    ]
